// DO NOT EDIT THIS FILE
// IT IS AUTO GENERATED BY ANGULAR-CLI
import {ArtistRoot} from './artist/artist-root.component';

export const CliRouteConfig = [
  {path: '/artist/...', name: 'ArtistRoot', component: ArtistRoot, useAsDefault: true},
];